spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: ychat
  datasource:
    url: jdbc:mysql://${ychat.mysql.host}:${ychat.mysql.port}/${ychat.mysql.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${ychat.mysql.username}
    password: ${ychat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${ychat.redis.host}
    # Redis服务器端口号
    port: ${ychat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${ychat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
wx:
  mp:
    callback: ${ychat.wx.callback}
    configs:
      - appId: ${ychat.wx.appId} # 第一个公众号的 appid
        secret: ${ychat.wx.secret} # 公众号的 appsecret
        token: ${ychat.wx.token} # 接口配置里的 Token 值
        aesKey: ${ychat.wx.aesKey} # 接口配置里的 EncodingAESKey 值

jwt:
  secret: ${ychat.jwt.secret}

# mybatis-plus配置控制台打印完整带参数 SQL 语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl