spring:
  profiles:
    # 运行环境
    active: test
  application:
    name: ychat
  datasource:
    url: jdbc:mysql://139.224.188.112:3306/ychat?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: zyj2021823
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  redis:
    # Redis服务器地址
    host: ${ychat.redis.host}
    # Redis服务器端口号
    port: ${ychat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${ychat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
wx:
  mp:
    callback: ${ychat.wx.callback}
    configs:
      - appId: ${ychat.wx.appId} # 第一个公众号的 appid
        secret: ${ychat.wx.secret} # 公众号的 appsecret
        token: ${ychat.wx.token} # 接口配置里的 Token 值
        aesKey: ${ychat.wx.aesKey} # 接口配置里的 EncodingAESKey 值

jwt:
  secret: ${ychat.jwt.secret}

# mybatis-plus配置控制台打印完整带参数 SQL 语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml